# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: NGS-Tents
author: Jay Gopalakrishnan
logo: figs/ngsTentsLogo.png
copyright : "2024"  # Copyright year to be placed in the footer

repository:
  url: https://github.com/jayggg/ngstents
  path_to_book: docs # Optional path to your book, relative to the repository root
  branch: gh-pages   # Which repo branch to use when creating links

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: auto
  timeout: 5000
  

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository

html:
  use_issues_button: false
  use_repository_button: true

parse:
  myst_enable_extensions:
  # See https://jupyterbook.org/en/stable/customize/config.html
    - html_image
    - dollarmath
    - amsmath
    - linkify
    - colon_fence
  myst_dmath_double_inline: true
  
